### ISSUE TITLE
Crash on old android on wallet restore 

### ISSUE THREAD

**Issue by NCrashed** [standardsats/wallet#13]
```
java.lang.IllegalStateException: Could not execute method of the activity
 at android.view.View$1.onClick(View.java:4290)
 at android.view.View.performClick(View.java:5246)
 at android.view.View$PerformClick.run(View.java:21256)
 at android.os.Handler.handleCallback(Handler.java:739)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:145)
 at android.app.ActivityThread.main(ActivityThread.java:6912)
 at java.lang.reflect.Method.invoke(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:372)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by: java.lang.reflect.InvocationTargetException
 at java.lang.reflect.Method.invoke(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:372)
 at android.view.View$1.onClick(View.java:4285)
 ... 10 more
Caused by: java.lang.NoSuchMethodError: No static method fromHtml(Ljava/lang/String;I)Landroid/text/Spanned; in class Landroid/text/Html; or its super classes (declaration of 'android.text.Html' appears in /system/framework/framework.jar:classes2.dex)
 at com.btcontract.walletfiat.BaseActivity$StringOps.html(BaseActivity.scala:63)
 at com.btcontract.walletfiat.BaseActivity$TitleView.<init>(BaseActivity.scala:379)
 at com.btcontract.walletfiat.BaseActivity$class.TitleView(BaseActivity.scala:374)
 at com.btcontract.walletfiat.SetupActivity.TitleView(SetupActivity.scala:43)
 at com.btcontract.walletfiat.SetupActivity.showMnemonicPopup(SetupActivity.scala:133)
 at com.btcontract.walletfiat.SetupActivity.useRecoveryPhrase(SetupActivity.scala:106)
 ... 13 more

java.lang.NoSuchMethodError: No static method fromHtml(Ljava/lang/String;I)Landroid/text/Spanned; in class Landroid/text/Html; or its super classes (declaration of 'android.text.Html' appears in /system/framework/framework.jar:classes2.dex)
 at com.btcontract.walletfiat.BaseActivity$StringOps.html(BaseActivity.scala:63)
 at com.btcontract.walletfiat.BaseActivity$TitleView.<init>(BaseActivity.scala:379)
 at com.btcontract.walletfiat.BaseActivity$class.TitleView(BaseActivity.scala:374)
 at com.btcontract.walletfiat.SetupActivity.TitleView(SetupActivity.scala:43)
 at com.btcontract.walletfiat.SetupActivity.showMnemonicPopup(SetupActivity.scala:133)
 at com.btcontract.walletfiat.SetupActivity.onActivityResult(SetupActivity.scala:73)
 at android.app.Activity.dispatchActivityResult(Activity.java:6833)
 at android.app.ActivityThread.deliverResults(ActivityThread.java:4730)
 at android.app.ActivityThread.handleSendResult(ActivityThread.java:4777)
 at android.app.ActivityThread.access$1500(ActivityThread.java:211)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1754)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:145)
 at android.app.ActivityThread.main(ActivityThread.java:6912)
 at java.lang.reflect.Method.invoke(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:372)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by NCrashed** [comment]
That Android version (5.0) is not supported
