### ISSUE TITLE
Crash when receiveing payment

### ISSUE THREAD

**Issue by evd0kim** [standardsats/wallet#26]
Report from Valet user:

```
java.lang.NullPointerException: Attempt to invoke interface method 'fr.acinq.eclair.wire.FullPaymentTag immortan.fsm.IncomingProcessorData.fullTag()' on a null object reference
 at immortan.ChannelMaster.finalizeIncoming(ChannelMaster.scala:155)
 at immortan.fsm.IncomingPaymentReceiver.doProcess(IncomingPaymentProcessor.scala:56)
 at immortan.ChannelMaster$$anonfun$notifyResolvers$3.apply(ChannelMaster.scala:364)
 at immortan.ChannelMaster$$anonfun$notifyResolvers$3.apply(ChannelMaster.scala:364)
 at scala.collection.Iterator$class.foreach(Iterator.scala:891)
 at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
 at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:206)
 at immortan.ChannelMaster.notifyResolvers(ChannelMaster.scala:364)
 at immortan.Channel$$anon$1$$anonfun$notifyResolvers$1.apply(Channel.scala:99)
 at immortan.Channel$$anon$1$$anonfun$notifyResolvers$1.apply(Channel.scala:99)
 at scala.collection.immutable.Set$Set2.foreach(Set.scala:128)
 at immortan.Channel$$anon$1.notifyResolvers(Channel.scala:99)
 at immortan.ChannelHosted.attemptInitResync(ChannelHosted.scala:358)
 at immortan.ChannelHosted.doProcess(ChannelHosted.scala:236)
 at immortan.Channel$$anonfun$process$1.apply$mcV$sp(Channel.scala:66)
 at immortan.Channel$$anonfun$process$1.apply(Channel.scala:66)
 at immortan.Channel$$anonfun$process$1.apply(Channel.scala:66)
 at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
 at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:764)
 ```
 
 when trying to pay it from own LN node. 
 Device Lenovo tablet.

**Comment by evd0kim** [comment]
Closed due to upgrade to 4.2.0
